In order to use the NumPy library, it has to be imported.

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5,6,7,8,9]    # Python List
A = np.array([1,2,3,4,5,6,7,8,9])   # NumPy array

In [3]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Numpy Arrays

There are different ways to create NumPy arrays

In [5]:
# arange() 
# Syntax: np.arange(start,stop,step)

arr = np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

### Shape of a NumPy Array

In [7]:
# Shape is an attribute for np array
# To get the shape of an array, the shape attribute is used

arr = np.arange(0,101,5)
arr.shape

(21,)

In [8]:
# It shows that the array has 21 rows and 1 column 
# Row = 0
# Column = 1

### Reshaping an Array

An array can be reshaped by using the reshape() function i.e it changes the dimension of the array

In [9]:
# Note: The number of column of the first matrix must be equal to the number of row of the second or vice versa

arr = np.arange(0,101,5)
arr

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [10]:
arr.shape

(21,)

In [11]:
arr.reshape(3,7)

array([[  0,   5,  10,  15,  20,  25,  30],
       [ 35,  40,  45,  50,  55,  60,  65],
       [ 70,  75,  80,  85,  90,  95, 100]])

In [13]:
# Creating an array filled with zeros

a = np.zeros((2,5))

In [14]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
# Creating an identity matrix
b = np.eye(6)
# Returns an identity matrix with the specified dimensions

In [16]:
b

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Adding Elements of a Matrix

In [20]:
M = np.arange(1,21,1)
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
np.sum(M)

210

In [24]:
# You can also specify the axis to be summed
m = M.reshape(5,4)
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [25]:
np.sum(m, axis = 1)  # Summing along rows

array([10, 26, 42, 58, 74])

In [26]:
np.sum(m, axis = 0)  # Summing along columns

array([45, 50, 55, 60])

In [27]:
# Creating an array filled with ones
arr = np.ones(6)

In [28]:
arr

array([1., 1., 1., 1., 1., 1.])

In [29]:
# linspace() function returns numbers evenly spaced over specified intervals
# Syntax: np.linspace(start, finish, equal no of points)
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

### Generating an array of random numbers in NumPy

We can generate an array of random numbers using rand(),randn() or randint() functions

In [30]:
np.random.rand(5)

array([0.68304594, 0.57146936, 0.12977827, 0.55404206, 0.17238294])

In [33]:
np.random.randint(6)

4

In [34]:
np.random.randint(1,15)

4

In [35]:
np.random.randint(1,15,10)

array([ 3,  5, 10,  3,  8,  7, 10, 12, 10, 14])

In [36]:
np.random.randn(7)

array([-0.9451429 , -2.02484702, -0.73834284, -0.36134798, -1.28933087,
       -0.62111988,  0.30873591])

### Locating maximum and minimum values of a NumPy array

In [37]:
a = np.arange(1,50,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [38]:
a.max()

49

In [39]:
a.min()

1

In [40]:
a.argmax()  # shows index of the highest number in the array

24

In [41]:
a.argmin()  # shows index of the lowest number in the array

0